_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
algorithm:
    value: PPO
batch_size:
    value: 256
ent_coef:
    value: 0.005
gae_lambda:
    value: 0.98
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
max_grad_norm:
    value: 0.5
n_epochs:
    value: 30
n_steps:
    value: 4096
policy_kwargs:
    value:
        activation_fn: torch.nn.modules.activation.ReLU
        net_arch:
            pi:
                - 512
                - 256
                - 128
            vf:
                - 512
                - 256
                - 128
        ortho_init: true
vf_coef:
    value: 2
