_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
alpha:
    value: 0.15
batch_size:
    value: 128
exploration_decay:
    value: 0.997
gamma:
    value: 0.97
learning_rate:
    value: 5e-05
total_timesteps:
    value: 50000
