_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 3
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
algorithm:
    value: PPO
batch_size:
    value: 512
ent_coef:
    value: 0.002
gae_lambda:
    value: 0.98
gamma:
    value: 0.995
learning_rate:
    value: 5e-05
max_grad_norm:
    value: 0.3
n_epochs:
    value: 40
n_steps:
    value: 8192
policy_kwargs:
    value:
        activation_fn: torch.nn.modules.activation.ReLU
        net_arch:
            pi:
                - 1024
                - 512
                - 256
            vf:
                - 1024
                - 512
                - 256
        ortho_init: true
vf_coef:
    value: 2.5
